#!/usr/bin/env bash
set -e

BUILD_DIR="./build"

if [ ! -d "$BUILD_DIR" ]; then
    cmake --preset=default
fi

if [ -z "$1" ]; then
    echo "Usage: $0 <target>"
    echo "Usage: $0 test <target>"
    exit 1
fi

TARGET="$1"

if [ "$TARGET" = "all" ]; then
  ninja -C "$BUILD_DIR"
  exit 0;
fi

if [ "$TARGET" = "test" ]; then
  if [ -z "$2" ]; then
    echo "Usage: $0 test <target>"
    exit 1
  fi
  TARGET="${2}_test"
  TARGET=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]')
fi

ninja -C "$BUILD_DIR" "$TARGET" && echo "Compilation success"

# Run executable if it exists
EXEC="$BUILD_DIR/bin/$TARGET"
if [ -x "$EXEC" ]; then
  "$EXEC"
else
  echo "Executable not found: $EXEC"
  exit 1
fi
